Repository Ureka-miniProject/AnalDoo-BE, pull requests merged in 2025-05, with the labels that each got.

#2 feat: 도메인 엔티티(User, Competition, Reservation) 및 연관관계 매핑 추가
  src/main/java/com/Ureka/AnalDoo/domain/entity/Address.java
  src/main/java/com/Ureka/AnalDoo/domain/entity/Competition.java
  src/main/java/com/Ureka/AnalDoo/domain/entity/CompetitionPeriod.java
  src/main/java/com/Ureka/AnalDoo/domain/entity/CompetitionStatus.java
  src/main/java/com/Ureka/AnalDoo/domain/entity/Reservation.java
  src/main/java/com/Ureka/AnalDoo/domain/entity/SocialType.java
  src/main/java/com/Ureka/AnalDoo/domain/entity/SportType.java
  src/main/java/com/Ureka/AnalDoo/domain/entity/User.java
Labels: feat

#7 [FEAT] 결제 기능 구현
  build.gradle
  src/main/java/com/Ureka/AnalDoo/common/config/WebConfig.java
  src/main/java/com/Ureka/AnalDoo/common/exception/errorcode/CommonErrorCode.java
  src/main/java/com/Ureka/AnalDoo/common/exception/errorcode/PaymentErrorCode.java
  src/main/java/com/Ureka/AnalDoo/common/exception/errorcode/ReservationErrorCode.java
  src/main/java/com/Ureka/AnalDoo/domain/entity/PayMethod.java
  src/main/java/com/Ureka/AnalDoo/domain/entity/Payment.java
  src/main/java/com/Ureka/AnalDoo/domain/entity/PaymentStatus.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/config/IamPortClientConfig.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/controller/PaymentController.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/dto/PaymentPrepareInfoResponse.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/dto/PaymentVerificationRequest.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/repository/PaymentRepository.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/service/PaymentService.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/service/PortOnePaymentServiceImpl.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/Ureka/AnalDoo/domain/user/repository/UserRepository.java
Labels: feat

#10 [FEAT] 대회 생성 기능 구현
  src/main/java/com/Ureka/AnalDoo/domain/competition/controller/CompetitionController.java
  src/main/java/com/Ureka/AnalDoo/domain/competition/dto/request/CompetitionCreateRequest.java
  src/main/java/com/Ureka/AnalDoo/domain/competition/dto/response/CompetitionCreateResponse.java
  src/main/java/com/Ureka/AnalDoo/domain/competition/repository/CompetitionRepository.java
  src/main/java/com/Ureka/AnalDoo/domain/competition/service/CompetitionService.java
  src/main/java/com/Ureka/AnalDoo/domain/user/repository/UserRepository.java
Labels: feat

#17 refactor: 지역을 ENUM 처리
  src/main/java/com/Ureka/AnalDoo/domain/competition/dto/request/CompetitionCreateRequest.java
  src/main/java/com/Ureka/AnalDoo/domain/competition/dto/response/CompetitionCreateResponse.java
  src/main/java/com/Ureka/AnalDoo/domain/entity/Address.java
  src/main/java/com/Ureka/AnalDoo/domain/entity/Local.java
Labels: refactor

#26 [TEST] userFixture 수정
  .github/workflows/develop-ci.yml
  src/test/java/com/Ureka/AnalDoo/domain/reservation/service/ReservationConcurrencyTest.java
  src/test/java/com/Ureka/AnalDoo/domain/reservation/service/ReservationServiceTest.java
  src/test/java/com/Ureka/AnalDoo/fixture/UserFixture.java
Labels: fix, test

#28 refactor: User 식별 이메일로 변경
  src/main/java/com/Ureka/AnalDoo/common/exception/errorcode/PaymentErrorCode.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/controller/PaymentController.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/service/PaymentService.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/service/PortOnePaymentServiceImpl.java
  src/main/java/com/Ureka/AnalDoo/domain/user/repository/UserRepository.java
Labels: refactor

#30 [FEAT] 대회 삭제 및 예약 해제 기능
  src/main/java/com/Ureka/AnalDoo/common/exception/errorcode/CompetitionErrorCode.java
  src/main/java/com/Ureka/AnalDoo/domain/competition/controller/CompetitionController.java
  src/main/java/com/Ureka/AnalDoo/domain/competition/repository/CompetitionRepository.java
  src/main/java/com/Ureka/AnalDoo/domain/competition/service/CompetitionService.java
  src/main/java/com/Ureka/AnalDoo/domain/entity/Competition.java
  src/main/java/com/Ureka/AnalDoo/domain/entity/Reservation.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/controller/PaymentController.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/dto/PaymentCancelResponse.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/service/PaymentService.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/service/PortOnePaymentServiceImpl.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/controller/ReservationController.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/service/ReservationService.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/service/ReservationServiceImpl.java
Labels: feat

#33 [CHORE] 배포
  .github/workflows/develop-ci.yml
  .github/workflows/develop-cicd.yml
  Dockerfile
  src/main/java/com/Ureka/AnalDoo/domain/reservation/dto/request/ReservationCreateRequest.java
Labels: fix, chore

#40 [FIX] authentication에 따라 변경
  src/main/java/com/Ureka/AnalDoo/domain/reservation/controller/ReservationController.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/service/ReservationService.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/service/ReservationServiceImpl.java
  src/test/java/com/Ureka/AnalDoo/domain/reservation/service/ReservationConcurrencyTest.java
  src/test/java/com/Ureka/AnalDoo/domain/reservation/service/ReservationServiceTest.java
Labels: fix

#44 [FIX] 예약 생성 예외 추가
  src/main/java/com/Ureka/AnalDoo/common/exception/errorcode/ReservationErrorCode.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/service/ReservationServiceImpl.java
  src/test/java/com/Ureka/AnalDoo/domain/reservation/service/ReservationServiceTest.java
  src/test/java/com/Ureka/AnalDoo/fixture/CompetitionFixture.java
  src/test/java/com/Ureka/AnalDoo/fixture/PaymentFixture.java
Labels: fix

#41 feat: 대회 상세 조회 구현
  src/main/java/com/Ureka/AnalDoo/domain/competition/controller/CompetitionController.java
  src/main/java/com/Ureka/AnalDoo/domain/competition/dto/response/CompetitionDetailResponse.java
  src/main/java/com/Ureka/AnalDoo/domain/competition/service/CompetitionService.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/repository/ReservationRepository.java
Labels: feat

#49 [Refactor] payment 구조 변경
  src/main/java/com/Ureka/AnalDoo/common/exception/GlobalExceptionHandler.java
  src/main/java/com/Ureka/AnalDoo/common/exception/PaymentGateWayException.java
  src/main/java/com/Ureka/AnalDoo/domain/competition/service/CompetitionService.java
  src/main/java/com/Ureka/AnalDoo/domain/entity/Payment.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/controller/PaymentController.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/dto/PaymentInfoDTO.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/dto/PaymentPrepareInfoResponse.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/service/PaymentDomainService.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/service/PaymentDomainServiceImpl.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/service/PaymentFacade.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/service/PaymentProviderService.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/service/PaymentService.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/service/PortOnePaymentServiceImpl.java
  src/main/java/com/Ureka/AnalDoo/domain/payment/service/PortOneServiceImpl.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/service/ReservationServiceImpl.java
Labels: refactor

#46 마이페이지 대회 조회
  src/main/java/com/Ureka/AnalDoo/auth/config/SecurityConfig.java
  src/main/java/com/Ureka/AnalDoo/auth/controller/MainController.java
  src/main/java/com/Ureka/AnalDoo/auth/jwt/JWTFilter.java
  src/main/java/com/Ureka/AnalDoo/auth/jwt/JwtExceptionFilter.java
  src/main/java/com/Ureka/AnalDoo/auth/service/AuthService.java
  src/main/java/com/Ureka/AnalDoo/common/exception/errorcode/CompetitionErrorCode.java
  src/main/java/com/Ureka/AnalDoo/domain/competition/dto/response/MyCreatedCompetitionResponse.java
  src/main/java/com/Ureka/AnalDoo/domain/competition/repository/CompetitionRepository.java
  src/main/java/com/Ureka/AnalDoo/domain/competition/service/CompetitionService.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/dto/response/MyJoinedCompetitionResponse.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/service/ReservationService.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/service/ReservationServiceImpl.java
  src/main/java/com/Ureka/AnalDoo/domain/user/controller/UserController.java
Labels: feat

#56 refactor: 대회 아이디로 예약 삭제
  src/main/java/com/Ureka/AnalDoo/domain/reservation/controller/ReservationController.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/service/ReservationService.java
  src/main/java/com/Ureka/AnalDoo/domain/reservation/service/ReservationServiceImpl.java
Labels: refactor

#54 [refactor] 대회 response dto 수정
  src/main/java/com/Ureka/AnalDoo/domain/competition/dto/response/CompetitionDetailResponse.java
Labels: refactor
